# Generated by Django 5.1.3 on 2024-11-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('SiteID', models.AutoField(primary_key=True, serialize=False)),
                ('Site_num', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
