# Generated by Django 5.1.3 on 2024-12-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_editorregistrationcode_editortablepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditorCode',
        ),
    ]
