# Generated by Django 5.1.3 on 2024-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_editor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('siteNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('ST', 'Settlement'), ('BG', 'Burial Ground'), ('RS', 'Religious Site'), ('MS', 'Military Structure'), ('AS', 'Agricultural Site'), ('IS', 'Industrial Site'), ('RA', 'Rock Art Site'), ('UW', 'Underwater Site')], max_length=2)),
                ('terrain', models.CharField(choices=[('CO', 'Coastal'), ('DE', 'Desert'), ('FO', 'Forest'), ('GR', 'Grassland'), ('MT', 'Mountain'), ('RV', 'River Valley'), ('UR', 'Urban'), ('WE', 'Wetland')], max_length=2)),
                ('condition', models.CharField(choices=[('DS', 'Destroyed'), ('HD', 'Heavily Damaged'), ('PD', 'Partially Damaged'), ('FR', 'Fair Condition'), ('GD', 'Good Condition'), ('IN', 'Fully Intact')], default='FR', max_length=2)),
                ('stratification', models.PositiveIntegerField(blank=True, null=True)),
                ('surfaceVisibility', models.CharField(choices=[('NV', 'Not Visible'), ('PR', 'Poor (<25%)'), ('FR', 'Fair (25-50%)'), ('GD', 'Good (50-75%)'), ('EX', 'Excellent (>75%)')], default='FR', max_length=2)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
