# Generated by Django 5.1.6 on 2025-04-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_sites"),
    ]

    operations = [
        migrations.CreateModel(
            name="Areas",
            fields=[
                (
                    "areaNo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bags",
            fields=[
                (
                    "bagNo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bags",
            },
        ),
        migrations.CreateModel(
            name="Artifacts",
            fields=[
                (
                    "artifactNo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Artifacts",
            },
        ),
        migrations.CreateModel(
            name="Loci",
            fields=[
                (
                    "locus",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SD", "Sediment"),
                            ("WL", "Wall"),
                            ("FT", "Feature"),
                            ("FL", "Floor"),
                            ("HT", "Hearth"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("colour", models.CharField(max_length=50)),
                (
                    "inclusions",
                    models.CharField(
                        choices=[
                            ("TR", "Tree Roots"),
                            ("AS", "Ash"),
                            ("CH", "Charcoal"),
                            ("BR", "Brick"),
                            ("BO", "Bone"),
                            ("SH", "Shell"),
                            ("PO", "Pottery"),
                            ("ST", "Stone"),
                        ],
                        max_length=2,
                    ),
                ),
                ("compaction", models.CharField(max_length=50)),
                (
                    "roundness",
                    models.CharField(
                        choices=[
                            ("CB", "Cobble"),
                            ("PB", "Pebble"),
                            ("AN", "Angular"),
                            ("SA", "Subangular"),
                            ("RD", "Rounded"),
                            ("WR", "Well Rounded"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("LW", "Low"),
                            ("MD", "Moderate"),
                            ("HI", "High"),
                            ("VH", "Very High"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "texture",
                    models.CharField(
                        choices=[
                            ("CL", "Clay"),
                            ("SL", "Silt"),
                            ("SD", "Sand"),
                            ("LM", "Loam"),
                            ("SC", "Sandy Clay"),
                            ("SLC", "Silty Clay"),
                            ("SLM", "Sandy Loam"),
                            ("SILM", "Silty Loam"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "excavatedVolume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loci",
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "photoNo",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("photo", models.ImageField(upload_to="photos/")),
                ("photographer", models.CharField(max_length=100)),
                ("caption", models.TextField()),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loanee", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Active"),
                            ("RT", "Returned"),
                            ("OD", "Overdue"),
                            ("DM", "ReturnedDamaged"),
                            ("LT", "Lost"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("dateLoaned", models.DateField()),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "artifactNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loans",
                "unique_together": {("artifactNo", "loanee", "dateLoaned")},
            },
        ),
    ]
