# Generated by Django 5.1.6 on 2025-04-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_areas_bags_artifacts_loci_photos_loans"),
    ]

    operations = [
        migrations.CreateModel(
            name="BladeFlake_Tool",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "bladeCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PR", "Primary"),
                            ("SC", "Secondary"),
                            ("TR", "Tertiary"),
                            ("CR", "Crested"),
                            ("PL", "Plunging"),
                            ("HI", "Hinged"),
                            ("OS", "Overshot"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "toolType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SC", "Scraper"),
                            ("BR", "Burin"),
                            ("PT", "Point"),
                            ("BF", "Biface"),
                            ("KN", "Knife"),
                            ("MC", "Microlith"),
                            ("PF", "Perforator"),
                            ("NT", "Notch"),
                            ("DN", "Denticulate"),
                            ("AX", "Axe"),
                            ("AR", "Arrowhead"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "maxLength",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "maxWidth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "hardHammer",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("I", "Indeterminate")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "backingCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("PA", "Partial"),
                            ("CP", "Complete"),
                            ("AL", "Alternate"),
                            ("BF", "Bifacial"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "backingType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("AB", "Abrupt"),
                            ("SA", "Semi-abrupt"),
                            ("IV", "Invasive"),
                            ("PR", "Pressure"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "retouchCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("MG", "Marginal"),
                            ("IV", "Invasive"),
                            ("CV", "Covering"),
                            ("ST", "Stepped"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "retouchType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("SC", "Scalar"),
                            ("PA", "Parallel"),
                            ("SP", "Subparallel"),
                            ("DN", "Denticulated"),
                            ("NT", "Notched"),
                            ("PR", "Pressure"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "percentageOfT",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "rawMaterial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "Chert"),
                            ("FL", "Flint"),
                            ("OB", "Obsidian"),
                            ("QZ", "Quartz"),
                            ("QT", "Quartzite"),
                            ("BS", "Basalt"),
                            ("LS", "Limestone"),
                            ("SS", "Sandstone"),
                            ("JP", "Jasper"),
                            ("CH", "Chalcedony"),
                            ("RH", "Rhyolite"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "useWearResult",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("CT", "Cutting"),
                            ("SC", "Scraping"),
                            ("BO", "Boring"),
                            ("CH", "Chopping"),
                            ("PO", "Pounding"),
                            ("MX", "Mixed"),
                            ("IN", "Indeterminate"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "photos",
                    models.FileField(
                        blank=True, null=True, upload_to="lithics/tools/photos/"
                    ),
                ),
                (
                    "drawings",
                    models.FileField(
                        blank=True, null=True, upload_to="lithics/tools/drawings/"
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blade/Flake Tools",
            },
        ),
        migrations.CreateModel(
            name="Cores",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "coreCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SP", "Single Platform"),
                            ("MP", "Multiple Platform"),
                            ("BP", "Bipolar"),
                            ("DC", "Discoidal"),
                            ("PY", "Pyramidal"),
                            ("PR", "Prismatic"),
                            ("TS", "Tested"),
                            ("EX", "Exhausted"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "coreType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flake"),
                            ("BL", "Blade"),
                            ("MX", "Mixed"),
                            ("LV", "Levallois"),
                            ("MB", "Microblade"),
                            ("BF", "Biface"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "platformLength",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "platformWidth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "platformHeight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "platformCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PL", "Plain"),
                            ("FC", "Faceted"),
                            ("DH", "Dihedral"),
                            ("CT", "Cortical"),
                            ("CR", "Crushed"),
                            ("PF", "Punctiform"),
                            ("LN", "Linear"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "platformType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flat"),
                            ("AN", "Angled"),
                            ("CV", "Convex"),
                            ("CC", "Concave"),
                            ("IR", "Irregular"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "platformPrep",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("AB", "Abrasion"),
                            ("IS", "Isolation"),
                            ("FC", "Faceting"),
                            ("CP", "Complete"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "numVisibleFlakes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "stageOfUse",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IN", "Initial"),
                            ("IM", "Intermediate"),
                            ("EX", "Exhausted"),
                            ("RC", "Recycled"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "rawMaterial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "Chert"),
                            ("FL", "Flint"),
                            ("OB", "Obsidian"),
                            ("QZ", "Quartz"),
                            ("QT", "Quartzite"),
                            ("BS", "Basalt"),
                            ("LS", "Limestone"),
                            ("SS", "Sandstone"),
                            ("JP", "Jasper"),
                            ("CH", "Chalcedony"),
                            ("RH", "Rhyolite"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "geologicalCondition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PR", "Pristine"),
                            ("WE", "Weathered"),
                            ("PT", "Patinated"),
                            ("RL", "Rolled"),
                            ("TD", "Thermal Damage"),
                            ("CA", "Chemical Alteration"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "photos",
                    models.FileField(
                        blank=True, null=True, upload_to="lithics/cores/photos/"
                    ),
                ),
                (
                    "drawings",
                    models.FileField(
                        blank=True, null=True, upload_to="lithics/cores/drawings/"
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cores",
            },
        ),
        migrations.CreateModel(
            name="Debitage",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "debitageCode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flake"),
                            ("BL", "Blade"),
                            ("BT", "Bladelet"),
                            ("CH", "Chunk"),
                            ("CP", "Chip"),
                            ("SH", "Shatter"),
                            ("CT", "Core Trimming"),
                            ("BS", "Burin Spall"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "debitageType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PR", "Primary (>50% cortex)"),
                            ("SC", "Secondary (<50% cortex)"),
                            ("TR", "Tertiary (no cortex)"),
                            ("CR", "Core Rejuvenation"),
                            ("TC", "Technical Piece"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "maxLength",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "maxWidth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "hardHammer",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("I", "Indeterminate")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "softHammer",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("I", "Indeterminate")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "indirectPercussion",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "Yes"), ("N", "No"), ("I", "Indeterminate")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "geologicalCondition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PR", "Pristine"),
                            ("WE", "Weathered"),
                            ("PT", "Patinated"),
                            ("RL", "Rolled"),
                            ("TD", "Thermal Damage"),
                            ("CA", "Chemical Alteration"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "rawMaterial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "Chert"),
                            ("FL", "Flint"),
                            ("OB", "Obsidian"),
                            ("QZ", "Quartz"),
                            ("QT", "Quartzite"),
                            ("BS", "Basalt"),
                            ("LS", "Limestone"),
                            ("SS", "Sandstone"),
                            ("JP", "Jasper"),
                            ("CH", "Chalcedony"),
                            ("RH", "Rhyolite"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Debitage",
            },
        ),
        migrations.CreateModel(
            name="Glass",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                ("mcNo", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "artifactType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VS", "Vessel"),
                            ("BD", "Bead"),
                            ("WN", "Window"),
                            ("FR", "Fragment"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Glass",
            },
        ),
        migrations.CreateModel(
            name="Metal_Objects",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                ("mcNo", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "artifactType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CN", "Coin"),
                            ("JW", "Jewelry"),
                            ("TL", "Tool"),
                            ("WP", "Weapon"),
                            ("VS", "Vessel"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "metal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GD", "Gold"),
                            ("SV", "Silver"),
                            ("CP", "Copper"),
                            ("BZ", "Bronze"),
                            ("IR", "Iron"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Metal Objects",
            },
        ),
        migrations.CreateModel(
            name="Osteology",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BV", "Bovidae (Cattle, Sheep, Goats)"),
                            ("CV", "Cervidae (Deer)"),
                            ("EQ", "Equidae (Horse family)"),
                            ("CN", "Canidae (Dogs, Wolves)"),
                            ("HM", "Hominidae (Humans)"),
                            ("AV", "Aves (Birds)"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("genus", models.CharField(blank=True, max_length=50, null=True)),
                ("species", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "element",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CR", "Cranium"),
                            ("TH", "Tooth"),
                            ("VT", "Vertebra"),
                            ("LM", "Limb bone"),
                            ("PL", "Pelvis"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L", "Left"),
                            ("R", "Right"),
                            ("A", "Axial"),
                            ("U", "Unknown"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "portion",
                    models.CharField(
                        blank=True,
                        choices=[("CM", "Complete"), ("FR", "Fragment")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("percentComplete", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JV", "Juvenile"),
                            ("AD", "Adult"),
                            ("UN", "Unknown"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("I", "Indeterminate"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("SM", "Small"), ("MD", "Medium"), ("LG", "Large")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "modification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO", "None"),
                            ("CT", "Cut Marks"),
                            ("BR", "Burned"),
                            ("WK", "Worked"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Osteology",
            },
        ),
        migrations.CreateModel(
            name="Pottery_Bases",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "baseForm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flat"),
                            ("RD", "Rounded"),
                            ("RG", "Ring"),
                            ("DK", "Disk"),
                            ("PD", "Pedestal"),
                            ("FT", "Footed"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "baseStance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ST", "Stable"),
                            ("UN", "Unstable"),
                            ("RA", "Raised"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "baseProfile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flat"),
                            ("CV", "Concave"),
                            ("CX", "Convex"),
                            ("PT", "Pointed"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "baseJunction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CT", "Continuous"),
                            ("AG", "Angled"),
                            ("CR", "Carinated"),
                            ("ST", "Stepped"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "outsideBaseDiameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "insideBaseDiameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "baseHeight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "baseThickness",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "basePercentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pottery Bases",
            },
        ),
        migrations.CreateModel(
            name="Pottery_Handles",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "handleType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LP", "Loop"),
                            ("ST", "Strap"),
                            ("LG", "Lug"),
                            ("KB", "Knob"),
                            ("TB", "Tab"),
                            ("WB", "Wishbone"),
                            ("BK", "Basket"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "handleSection",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RD", "Round"),
                            ("OV", "Oval"),
                            ("RC", "Rectangular"),
                            ("SQ", "Squared"),
                            ("FL", "Flattened"),
                            ("GR", "Grooved"),
                            ("TW", "Twisted"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "handleAttachment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RB", "Rim to Body"),
                            ("RS", "Rim to Shoulder"),
                            ("SB", "Shoulder to Body"),
                            ("BB", "Body to Body"),
                            ("SA", "Single Attachment"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "handleLength",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "handleWidth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "handleThickness",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pottery Handles",
            },
        ),
        migrations.CreateModel(
            name="Pottery_Main",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RM", "Rim"),
                            ("BS", "Base"),
                            ("HD", "Handle"),
                            ("BD", "Body"),
                            ("NK", "Neck"),
                            ("SH", "Shoulder"),
                            ("SP", "Spout"),
                            ("CP", "Complete Vessel"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "mass",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pottery Main",
            },
        ),
        migrations.CreateModel(
            name="Pottery_Rims",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "rimForm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EV", "Everted"),
                            ("IN", "Inverted"),
                            ("ST", "Straight"),
                            ("LD", "Ledged"),
                            ("CO", "Collared"),
                            ("FL", "Flanged"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "rimStance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VT", "Vertical"),
                            ("FL", "Flaring"),
                            ("RS", "Restricted"),
                            ("CL", "Closed"),
                            ("OP", "Open"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "rimProfile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RD", "Rounded"),
                            ("SQ", "Squared"),
                            ("PT", "Pointed"),
                            ("TH", "Thickened"),
                            ("BV", "Bevelled"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "rimLipShape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FL", "Flat"),
                            ("RD", "Rounded"),
                            ("PT", "Pointed"),
                            ("TH", "Thickened"),
                            ("TP", "Tapered"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "rimLipSymmetry",
                    models.CharField(
                        blank=True,
                        choices=[("SY", "Symmetric"), ("AS", "Asymmetric")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "outsideRimDiameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "insideRimDiameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "rimHeight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "rimThickness",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "neckHeight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "neckDiameter",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "rimPercentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pottery Rims",
            },
        ),
        migrations.CreateModel(
            name="Special_Finds",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                ("mcNo", models.CharField(blank=True, max_length=30, null=True)),
                ("description", models.TextField()),
                ("comments", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Special Finds",
            },
        ),
        migrations.CreateModel(
            name="Worked_Bone",
            fields=[
                (
                    "artifactNo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="myapp.artifacts",
                    ),
                ),
                (
                    "artifactType",
                    models.CharField(
                        blank=True,
                        choices=[("TL", "Tool"), ("OR", "Ornament"), ("OT", "Other")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("mcNo", models.CharField(blank=True, max_length=30, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "areaNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.areas"
                    ),
                ),
                (
                    "bagNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.bags"
                    ),
                ),
                (
                    "related_osteology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worked_bone",
                        to="myapp.osteology",
                    ),
                ),
                (
                    "siteNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.sites"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Worked Bone",
            },
        ),
    ]
