# Generated by Django 5.1.6 on 2025-04-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_bladeflake_tool_cores_debitage_glass_metal_objects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DS", "Destroyed"),
                    ("HD", "Heavily Damaged"),
                    ("PD", "Partially Damaged"),
                    ("FR", "Fair Condition"),
                    ("GD", "Good Condition"),
                    ("IN", "Fully Intact"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sites",
            name="stratification",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="sites",
            name="surfaceVisibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NV", "Not Visible"),
                    ("PR", "Poor (<25%)"),
                    ("FR", "Fair (25-50%)"),
                    ("GD", "Good (50-75%)"),
                    ("EX", "Excellent (>75%)"),
                    ("BR", "Bare Rock"),
                    ("CU", "Cultivated"),
                    ("BC", "Bare rock, cult."),
                    ("RG", "Regular"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="terrain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HL", "Hill"),
                    ("SL", "Slope"),
                    ("RD", "Ridge"),
                    ("VL", "Valley"),
                    ("CO", "Coastal"),
                    ("DE", "Desert"),
                    ("FO", "Forest"),
                    ("GR", "Grassland"),
                    ("MT", "Mountain"),
                    ("RV", "River Valley"),
                    ("UR", "Urban"),
                    ("WE", "Wetland"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sites",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ST", "Settlement"),
                    ("BG", "Burial Ground"),
                    ("RS", "Religious Site"),
                    ("MS", "Military Structure"),
                    ("AS", "Agricultural Site"),
                    ("IS", "Industrial Site"),
                    ("RA", "Rock Art Site"),
                    ("UW", "Underwater Site"),
                    ("LS", "Lithic Scatter"),
                    ("SS", "Sherd Scatter"),
                    ("CE", "Cemetery"),
                    ("TB", "Tomb or Cemetery"),
                    ("KH", "Khirbah"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
