# Generated by Django 5.1.6 on 2025-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_sites_condition_alter_sites_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DS", "Destroyed"),
                    ("HD", "Heavily Damaged"),
                    ("PD", "Partially Damaged"),
                    ("FR", "Fair Condition"),
                    ("GD", "Good Condition"),
                    ("IN", "Fully Intact"),
                    ("PS", "Pasture"),
                    ("PF", "Plowed field"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
