# Generated by Django 5.1.6 on 2025-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_sites_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loci",
            name="type",
            field=models.CharField(
                choices=[
                    ("SL", "Soil"),
                    ("SF", "Surface"),
                    ("CL", "Collapse"),
                    ("PF", "Pit fill"),
                    ("WS", "Wall/Stone feature"),
                    ("VS", "Virgin Soil"),
                    ("BT", "Baulk trim"),
                    ("OT", "Other"),
                ],
                max_length=2,
            ),
        ),
    ]
