# Generated by Django 5.2 on 2025-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_loci_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bags",
            options={},
        ),
        migrations.AlterModelOptions(
            name="loci",
            options={},
        ),
        migrations.AddField(
            model_name="loci",
            name="bag_nos",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="highest_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loci",
            name="locus_above",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="locus_below",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="locus_equals_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="locus_equals_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="lowest_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loci",
            name="num_gufaf",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="strat_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loci",
            name="vol_gufaf",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loci",
            name="vol_levels",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loci",
            name="colour",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loci",
            name="compaction",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="loci",
            name="density",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LW", "Low"),
                    ("MD", "Moderate"),
                    ("HI", "High"),
                    ("VH", "Very High"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loci",
            name="inclusions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TR", "Tree Roots"),
                    ("AS", "Ash"),
                    ("CH", "Charcoal"),
                    ("BR", "Brick"),
                    ("BO", "Bone"),
                    ("SH", "Shell"),
                    ("PO", "Pottery"),
                    ("ST", "Stone"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loci",
            name="roundness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CB", "Cobble"),
                    ("PB", "Pebble"),
                    ("AN", "Angular"),
                    ("SA", "Subangular"),
                    ("RD", "Rounded"),
                    ("WR", "Well Rounded"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loci",
            name="texture",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CL", "Clay"),
                    ("SL", "Silt"),
                    ("SD", "Sand"),
                    ("LM", "Loam"),
                    ("SC", "Sandy Clay"),
                    ("SLC", "Silty Clay"),
                    ("SLM", "Sandy Loam"),
                    ("SILM", "Silty Loam"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
