# Generated by Django 5.2 on 2025-04-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_bags_options_alter_loci_options_loci_bag_nos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loci",
            name="bag_nos",
        ),
        migrations.RemoveField(
            model_name="loci",
            name="locus_above",
        ),
        migrations.RemoveField(
            model_name="loci",
            name="locus_below",
        ),
        migrations.RemoveField(
            model_name="loci",
            name="locus_equals_1",
        ),
        migrations.RemoveField(
            model_name="loci",
            name="locus_equals_2",
        ),
    ]
